--hints: off
--debuginfo
--run
--threads:on
--define:"debugLogging=on"
--define:"chronicles_disable_thread_id"
--define:"async_backend=asyncdispatch"
--define:"chronicles_timestamps=None"
--define:"debugLogging"
