--hints: off
--debuginfo
--threads:on
--define:"debugLogging=on"
--define:"chronicles_thread_ids=no"
--define:"async_backend=asyncdispatch"
--define:"chronicles_timestamps=None"
--define:"debugLogging"
--define:"test"
