on:
  push:
  pull_request:
  schedule:
  - cron: "0 19 * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-15-intel
          # https://github.com/nim-lang/setup-nimble-action/issues/13
          # - macos-latest
          - windows-latest
    name: CI / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CACHE_NONCE: "20260914"
    steps:
      - uses: actions/checkout@v6
      - name: Setup Nimble
        uses: nim-lang/setup-nimble-action@v1
        with:
          nimble-version: "latest"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore nimble dependencies from cache
        id: nimble_deps
        uses: actions/cache@v5
        with:
          path: nimbledeps
          key: nimble-deps-${{ env.CACHE_NONCE }}-${{ runner.os }}-${{ runner.arch }}-${{ matrix.os }}-${{ hashFiles('**/nimble.lock') }}

      - name: Install dependencies
        shell: bash
        run: nimble -yld install

      - name: Nimble Test
        shell: bash
        run: nimble test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check `nph` formatting
        uses: arnetheduck/nph-action@v1
        with:
          version: 0.7.0
          options: "*.nim protocol"
          fail: true
          suggest: true
